# This file configures the analyzer to use the lint rule set from `package:lint`

include: package:lint/package.yaml

analyzer:
  errors:
    public_member_api_docs: warning

# Adjusted linting rules
linter:
  rules:
    always_use_package_imports: false
    prefer_relative_imports: true
    prefer_double_quotes: true
    sort_constructors_first: true
    unawaited_futures: true
    public_member_api_docs: true
    comment_references: true
    unnecessary_lambdas: true
    lines_longer_than_80_chars: true
    avoid_catches_without_on_clauses: true
    use_to_and_as_if_applicable: true
    avoid_returning_this: true
    avoid_types_on_closure_parameters: true
    avoid_slow_async_io: true
    close_sinks: true
    cascade_invocations: true
    only_throw_errors: true
    unnecessary_library_name: true
    always_put_required_named_parameters_first: true
